allow nginx reload to fail during configure
reason: when certificates for HTTPS move, nginx reload will fail while
some nginx config files still reference /etc/nginx/ssl

diff --git a/debian/xivo-dird.postinst b/debian/xivo-dird.postinst
--- a/debian/xivo-dird.postinst
+++ b/debian/xivo-dird.postinst
@@ -26,10 +26,11 @@ case "$1" in
 		# Return 100 if nginx is not installed (which is valid, think docker).
 		invoke-rc.d --query --quiet nginx reload
 		status=$?
-		set -e
 		if [ $status -ne 100 ] ; then
+			# May temporarily fail during upgrade because SSL certs have moved.
 			invoke-rc.d nginx reload
 		fi
+		set -e
 	;;
 
 	abort-upgrade|abort-remove|abort-deconfigure)
